name: GitHub Actions Secret MAVEN

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env: # lookup key as an environment variable
        IEX_TOKEN: ${{ secrets.GH_TEST }}
      run: mvn -B package --file pom.xml
